name: Run Tests # Meaningless change to trigger pipeline using push

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: "Unit tests: javaVersion on Java code"
        working-directory: ./javaVersion
        run: |
          chmod +x gradlew
          ./gradlew test
          echo "Running javaVersion's unit tests on itself..."