name: Run Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Debug: Show me the files"
        run: |
          echo "Current location:"
          pwd
          echo "Listing all files in the repository:"
          find . -maxdepth 2 -not -path '*/.*'

      - name: "Unit tests: javaVersion on Java code"
        continue-on-error: true
        working-directory: ./javaVersion
        run: |
          chmod +x ./gradlew
          ./gradlew test

      - name: "Unit tests: kotlinVersion on Kotlin code"
        continue-on-error: true
        working-directory: ./kotlinVersion
        run: |
          chmod +x ./gradlew
          ./gradlew test

# TODO: Ideally execute J2K here inline (without extra j2kVersion folder to save space)
## In that case, update all references to j2kVersion to javaVersion in block below

      - name: "Unit tests: j2kVersion on j2k code"
        continue-on-error: true
        working-directory: ./j2kVersion
        run: |
          chmod +x ./gradlew
          ./gradlew test

      - name: "Ktlint: j2k code"
        continue-on-error: true
        working-directory: ./j2kVersion
        run: |
          chmod +x ./gradlew
          ./gradlew ktlintCheck

## End of block

      - name: "Checkstyle: Java code"
        continue-on-error: true
        working-directory: ./javaVersion
        run: |
          chmod +x ./gradlew
          ./gradlew checkstyleMain